from __future__ import annotations

import random
import re
import time

FLASH_LITE_MODEL = "gemini-2.5-flash"

_RETRY_IN_RE = re.compile(r"retry in\s+([0-9]+(?:\.[0-9]+)?)s", flags=re.IGNORECASE)
_RETRY_DELAY_RE = re.compile(r"retry_delay\s*\{\s*seconds:\s*([0-9]+)", flags=re.IGNORECASE)

_FINAL_SUMMARY_PROMPT = """You are a Senior Construction Contract Analyst. Your task is to synthesize a final, comprehensive contract review summary from a set of compiled extraction notes.

The provided text is NOT the raw contract. It is a concatenated list of extracted facts and quoted clauses generated by an AI auditor.

CRITICAL RULES:
1. DEDUPLICATE & SYNTHESIZE: The auditor reviewed the contract in overlapping windows, so many clauses will appear multiple times. Combine duplicated facts into a single, clear bullet point.
2. PRESERVE CITATIONS (MANDATORY): The input notes contain citations formatted as [chunk_<id>]. You MUST append all relevant chunk IDs to the end of every bullet point in your final summary. If you combine duplicate facts, include ALL unique chunk IDs associated with that fact (e.g., [chunk_12, chunk_14]).
3. NO HALLUCINATIONS: Use ONLY the provided notes. Do not invent facts, dates, or values.
4. CLARITY OVER VERBOSITY: Write in a professional, concise legal/business tone.

OUTPUT FORMAT:

## 1. Top Issues & Executive Summary
- Start with a short paragraph identifying the most important risks or unusual terms.
- Prioritize payment risk, strict indemnity, aggressive schedule constraints, and critical missing information.

## 2. Key Contract Overview
Include (if found in the notes):
- Project Name:
- General Contractor:
- Subcontractor:
- Contract Value:
- Retainage %:
- Governing Law:

## 3. Scope & Project Execution
- Summarize the main scope of work.
- List major inclusions and exclusions.
- List items explicitly furnished by others (GC/Owner).
- Note any referenced exhibits affecting the scope.

## 4. Schedule & Delay Risk
- Start dates / milestones / completion dates.
- Extract any "time is of the essence" language.
- Liquidated damages (amounts or pass-through obligations).
- Delay provisions (including notice requirements and "no-damages-for-delay" clauses).

## 5. Financial & Payment Terms (CRITICAL)
- Pay-if-paid vs. pay-when-paid language.
- Condition precedent language.
- Payment cycle, timing, and billing requirements (e.g., Procore usage).
- Lien waiver requirements.
- Withholding / offsets / backcharge rules.

## 6. Insurance & Indemnity
- Type of indemnity (broad / limited / employee injury exposure).
- Defense obligations.
- Specific insurance limits (GL, Auto, WC, Professional).
- Additional insured or Waiver of Subrogation requirements.

## 7. Legal, Default & Disputes
- Termination for cause / convenience and cure periods.
- Dispute resolution method (e.g., Arbitration, Litigation).
- Venue and governing law.
- Incorporation of the Prime Contract / Flow-down clauses.

## 8. Compliance & Safety
- Specific safety requirements (e.g., OSHA, THA forms, drug policies).
- Project-specific compliance obligations.

## 9. Missing or Unclear Items
- Explicitly list important standard contract items that were NOT found in the extraction notes (e.g., "No liquidated damages clause identified," or "Warranty period not specified").

COMPILED EXTRACTION NOTES:
{concatenated_gemma_notes_go_here}
"""


def _extract_retry_delay_seconds(exc: Exception) -> float | None:
    msg = str(exc)
    m = _RETRY_IN_RE.search(msg)
    if m:
        try:
            return float(m.group(1))
        except ValueError:
            return None
    m = _RETRY_DELAY_RE.search(msg)
    if m:
        try:
            return float(m.group(1))
        except ValueError:
            return None
    return None


def synthesize_final_summary_with_meta(
    concatenated_gemma_notes: str,
    *,
    api_key: str,
    max_attempts: int = 6,
) -> tuple[str, object]:
    import google.generativeai as genai

    genai.configure(api_key=api_key)
    model = genai.GenerativeModel(FLASH_LITE_MODEL)
    prompt = _FINAL_SUMMARY_PROMPT.format(
        concatenated_gemma_notes_go_here=concatenated_gemma_notes
    )

    initial_backoff_s = 1.0
    max_backoff_s = 45.0
    for attempt in range(max_attempts):
        try:
            resp = model.generate_content(prompt)
            return str(getattr(resp, "text", "") or "").strip(), resp
        except Exception as exc:
            if attempt == max_attempts - 1:
                raise
            exp_wait_s = min(max_backoff_s, initial_backoff_s * (2**attempt))
            quota_wait_s = _extract_retry_delay_seconds(exc)
            wait_s = max(exp_wait_s, quota_wait_s or 0.0) + random.uniform(0.2, 1.0)
            time.sleep(wait_s)
    return "", None


def synthesize_final_summary(
    concatenated_gemma_notes: str,
    *,
    api_key: str,
    max_attempts: int = 6,
) -> str:
    text, _ = synthesize_final_summary_with_meta(
        concatenated_gemma_notes,
        api_key=api_key,
        max_attempts=max_attempts,
    )
    return text


__all__ = ["FLASH_LITE_MODEL", "synthesize_final_summary", "synthesize_final_summary_with_meta"]
